<a href="https://colab.research.google.com/github/pingao2019/DS-Unit-4-Sprint-1-NLP/blob/master/LS_DS_415_Sprint_Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<br></br>
<br></br>

# Sprint Challenge
## *Data Science Unit 4 Sprint 1*

After a week of Natural Language Processing, you've learned some cool new stuff: how to process text, how turn text into vectors, and how to model topics from documents. Apply your newly acquired skills to one of the most famous NLP datasets out there: [Yelp](https://www.yelp.com/dataset/challenge). As part of the job selection process, some of my friends have been asked to create analysis of this dataset, so I want to empower you to have a head start.  

The real dataset is massive (almost 8 gigs uncompressed). I've sampled the data for you to something more managable for the Sprint Challenge. You can analyze the full dataset as a stretch goal or after the sprint challenge. As you work on the challenge, I suggest adding notes about your findings and things you want to analyze in the future.

## Challenge Objectives
*Successfully complete these all these objectives to earn a 2. There are more details on each objective further down in the notebook.*
* <a href="#p1">Part 1</a>: Write a function to tokenize the yelp reviews
* <a href="#p2">Part 2</a>: Create a vector representation of those tokens
* <a href="#p3">Part 3</a>: Use your tokens in a classification model on yelp rating
* <a href="#p4">Part 4</a>: Estimate & Interpret a topic model of the Yelp reviews

In [0]:
#get dataset for analying.

import pandas as pd

yelp = pd.read_json('./data/review_sample.json', lines=True)
yelp.head()


business_id  cool                date  funny  \
0  nDuEqIyRc8YKS1q1fX0CZg     1 2015-03-31 16:50:30      0   
1  eMYeEapscbKNqUDCx705hg     0 2015-12-16 05:31:03      0   
2  6Q7-wkCPc1KF75jZLOTcMw     1 2010-06-20 19:14:48      1   
3  k3zrItO4l9hwfLRwHBDc9w     3 2010-07-13 00:33:45      4   
4  6hpfRwGlOzbNv7k5eP9rsQ     1 2018-06-30 02:30:01      0   

                review_id  stars  \
0  eZs2tpEJtXPwawvHnHZIgQ      1   
1  DoQDWJsNbU0KL1O29l_Xug      4   
2  DDOdGU7zh56yQHmUnL1idQ      3   
3  LfTMUWnfGFMOfOIyJcwLVA      1   
4  zJSUdI7bJ8PNJAg4lnl_Gg      4   

                                                text  useful  \
0  BEWARE!!! FAKE, FAKE, FAKE....We also own a sm...      10   
1  Came here for lunch Togo. Service was quick. S...       0   
2  I've been to Vegas dozens of times and had nev...       2   
3  We went here on a night where they closed off ...       5   
4  3.5 to 4 stars\n\nNot bad for the price, $12.9...       5   

                  user_id  
0  n1LM36qNg4rqGXIcvVXv8w  
1  5CgjjDAic2-FAvCtiHpytA  
2  BdV-cf3LScmb8kZ7iiBcMA  
3  cZZnBqh4gAEy4CdNvJailQ  
4  n9QO4ClYAS7h9fpQwa5bhA

In [0]:
yelp['text']

0       BEWARE!!! FAKE, FAKE, FAKE....We also own a sm...
1       Came here for lunch Togo. Service was quick. S...
2       I've been to Vegas dozens of times and had nev...
3       We went here on a night where they closed off ...
4       3.5 to 4 stars\n\nNot bad for the price, $12.9...
                              ...                        
9995    My family and I were hungry and this Subway is...
9996    My wife and I came here with a a couple of fri...
9997    The food was just OK and not anything to brag ...
9998    Today's visit is great!! Love and enjoy Town S...
9999    This is the absolute worst place I have ever s...
Name: text, Length: 10000, dtype: object

## Part 1: Tokenize Function
<a id="#p1"></a>

Complete the function `tokenize`. Your function should
- accept one document at a time
- return a list of tokens

You are free to use any method you have learned this week.


In [0]:
#  use SpaCy for tokenizing. 

from spacy.lang.en import English
nlp = English()
tokenizer = nlp.Defaults.create_tokenizer(nlp)

In [0]:


import spacy
from spacy.tokenizer import Tokenizer

nlp = spacy.load("en_core_web_lg")

# Tokenizer
tokenizer = Tokenizer(nlp.vocab)



In [0]:
STOP_WORDS = nlp.Defaults.stop_words.union(['\n\n', '\n', ' ',  'just',  'got', 'done', 'today', 'did', 'didn',  'came', 'definitely' ,'got', 'just','really','going', 'said' ])

In [0]:
def tokenize(doc):
    tokens_new = []
    tokens = tokenizer(doc)
    for token in tokens:
        if (token.is_punct == False) and (token.text.lower() not in STOP_WORDS):
            tokens_new.append(token.text.lower())
    return tokens_new

In [0]:
text_tokens = yelp['text'].apply(tokenize)

In [0]:
yelp['text_tokens'] = text_tokens

yelp['text_tokens'].head()

0    [beware!!!, fake,, fake,, fake....we, small, b...
1    [lunch, togo., service, quick., staff, friendl...
2    [i've, vegas, dozens, times, stepped, foot, ci...
3    [went, night, closed, street, party..., best, ...
4    [3.5, 4, stars, bad, price,, $12.99, lunch,, s...
Name: text_tokens, dtype: object

In [0]:
import squarify
import matplotlib.pyplot as plt
import seaborn as sns

In [0]:
# Analyzing Tokens, Object from Base Python
from collections import Counter

# The object `Counter` takes an iterable, but you can instaniate an empty one and update it. 
word_counts = Counter()

# Update it based on a split of each of our documents
yelp['text_tokens'].apply(lambda x: word_counts.update(x))

# Print out the 10 most common words
word_counts.most_common(30)

[('place', 3782),
 ('food', 3687),
 ('great', 3407),
 ('like', 3361),
 ('good', 3235),
 ("it's", 2696),
 ('service', 2573),
 ('time', 2497),
 ("don't", 1854),
 ('love', 1597),
 ('best', 1548),
 ("i'm", 1531),
 ("didn't", 1530),
 ("i've", 1513),
 ('went', 1445),
 ('ordered', 1438),
 ('come', 1428),
 ('little', 1395),
 ('nice', 1341),
 ('staff', 1272),
 ('order', 1231),
 ('try', 1225),
 ('it.', 1211),
 ('chicken', 1162),
 ('people', 1160),
 ('new', 1086),
 ('know', 1065),
 ('pretty', 1051),
 ('recommend', 1038),
 ('restaurant', 1018)]

## Part 2: Vector Representation
<a id="#p2"></a>
1. Create a vector representation of the reviews
2. Write a fake review and query for the 10 most similiar reviews, print the text of the reviews. Do you notice any patterns?
    - Given the size of the dataset, it will probably be best to use a `NearestNeighbors` model for this. 

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.neighbors import NearestNeighbors

In [0]:
# using CountVectorizer to see how many words in each document.

vect = CountVectorizer(stop_words='english')

vect.fit(yelp['text'])

dtm = vect.transform(yelp['text'])

In [0]:
dtm = pd.DataFrame(dtm.todense(), columns=vect.get_feature_names())

In [0]:


wc_top20 = pd.DataFrame(dtm.sum().sort_values(ascending=False).head(20),
                       columns=['count'])



In [0]:
wc_top20

count
food      5070
place     4832
good      4806
great     4297
service   3695
like      3558
just      3553
time      3449
really    2692
got       2070
don       1925
ve        1924
nice      1748
best      1746
did       1737
love      1685
staff     1597
order     1575
didn      1564
came      1553

### Use TF-IDF to vectorize. TF-IDF means Term Frequency - Inverse Document Frequency. Term Frequency: Percentage of words in document for each word.





In [0]:
tfidf = TfidfVectorizer(stop_words='english', max_features=5000)
# Create a vocabulary and get word counts per document.Similiar to fit_predict. Giving Percentage of words in document for each wor

dtm = tfidf.fit_transform(yelp['text'])
# Get feature names to use as dataframe column headers
dtm = pd.DataFrame(dtm.todense(), columns=tfidf.get_feature_names())
tfidf


TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=5000,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [0]:
dtm.shape

(10000, 5000)

In [0]:
#### View Feature Matrix as DataFrame
dtm.head()

00  000  00pm   07   10  100  1000  101  10pm   11  ...  yuck  yuk  yum  \
0  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  ...   0.0  0.0  0.0   
1  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  ...   0.0  0.0  0.0   
2  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  ...   0.0  0.0  0.0   
3  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  ...   0.0  0.0  0.0   
4  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  ...   0.0  0.0  0.0   

   yummy  yup  zero  zone  zoo  zucchini  était  
0    0.0  0.0   0.0   0.0  0.0       0.0    0.0  
1    0.0  0.0   0.0   0.0  0.0       0.0    0.0  
2    0.0  0.0   0.0   0.0  0.0       0.0    0.0  
3    0.0  0.0   0.0   0.0  0.0       0.0    0.0  
4    0.0  0.0   0.0   0.0  0.0       0.0    0.0  

[5 rows x 5000 columns]

In [0]:
# Fit a NearestNeighbors model(K-NN)
nn = NearestNeighbors(n_neighbors=5, algorithm='kd_tree')
nn.fit(dtm)


NearestNeighbors(algorithm='kd_tree', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [0]:
review = ['Wonderful burrito, great coffee, nice owner, convenient parking.']

In [0]:
new = tfidf.transform(review)

In [0]:
new.todense()

matrix([[0., 0., 0., ..., 0., 0., 0.]])

In [0]:
matches = nn.kneighbors(new.todense(), n_neighbors=10)[1]
for match in matches:
    print(yelp['text'][match])


6311    天氣很熱吃不下東西，今天我點了一個韓國冷面湯、餐後點了甜點，冰沙系列不會太甜膩，覺得店家很用...
6204    旅行でラスベガスに来ましたがネイルがはげてるのが気になり、探したお店でした。\n質問にも丁寧...
6029    Just discovered this place, a hidden treasure ...
4867    The ambiance of this place is a 4 or a 5- it's...
4536    Burritos are on the "smaller" side but still g...
5784    This is a great location. It's not as packed a...
6290    Great place for a decent burrito.\nLove the ca...
721     ordered a spicy bbq steak burrito. add topping...
4094    It's wonderful to find a coffee shop that care...
822     Bomb tacos! Menu is simplistic, but food is al...
Name: text, dtype: object


## Part 3: Classification
<a id="#p3"></a>
Your goal in this section will be to predict `stars` from the review dataset. 

1. Create a piepline object with a sklearn `CountVectorizer` or `TfidfVector` and any sklearn classifier. Use that pipeline to estimate a model to predict `stars`. Use the Pipeline to predict a star rating for your fake review from Part 2. 
2. Tune the entire pipeline with a GridSearch

In [0]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [0]:
vect = TfidfVectorizer(stop_words='english')
clf = RandomForestClassifier()

pipe = Pipeline([('vect', vect), ('clf', clf)])

In [0]:
yelp.columns.to_list()

['business_id',
 'cool',
 'date',
 'funny',
 'review_id',
 'stars',
 'text',
 'useful',
 'user_id',
 'text_tokens']

In [0]:
pipe.fit(yelp['text'], yelp['stars'])

Pipeline(memory=None,
         steps=[('vect',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words='english', strip_accents=None,
                                 sublinear_tf=False,
                                 token_patte...
                 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                        class_weight=None, criterion='gini',
                                        max_depth=None, max_features='auto',
                                        max_leaf_nodes=None, max_samples=None

In [0]:
bad_review = ['This place stinks, plain and simple. Worst calamari ever.']


In [0]:
pipe.predict(review)

array([5], dtype=int64)

In [0]:
pipe.predict(bad_review)

array([1], dtype=int64)

In [0]:
parameters = {
    'vect__max_df': (0.8, 0.9, 1.0),
    'vect__min_df': (.02, .05, .1),
#     'vect__max_features': (500,5000),
    'clf__n_estimators': (50, 100),
    'clf__max_depth': (20, 100, 200)
}

grid_search = GridSearchCV(pipe, parameters, cv=3, n_jobs=4, verbose=1)
grid_search.fit(yelp['text'], yelp['stars'])

Fitting 3 folds for each of 54 candidates, totalling 162 fits


[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:  1.2min
[Parallel(n_jobs=4)]: Done 162 out of 162 | elapsed:  7.0min finished


GridSearchCV(cv=3, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('vect',
                                        TfidfVectorizer(analyzer='word',
                                                        binary=False,
                                                        decode_error='strict',
                                                        dtype=<class 'numpy.float64'>,
                                                        encoding='utf-8',
                                                        input='content',
                                                        lowercase=True,
                                                        max_df=1.0,
                                                        max_features=None,
                                                        min_df=1,
                                                        ngram_range=(1, 1),
                                                        no

In [0]:

grid_search.predict(review)



array([5], dtype=int64)

In [0]:
grid_search.predict(bad_review)

## Part 4: Topic Modeling

Let's find out what those yelp reviews are saying! :D

1. Estimate a LDA topic model of the review text
    - Keep the `iterations` parameter at or below 5 to reduce run time
    - The `workers` parameter should match the number of physical cores on your machine.
2. Create 1-2 visualizations of the results
    - You can use the most important 3 words of a topic in relevant visualizations. Refer to yesterday's notebook to extract. 
3. In markdown, write 1-2 paragraphs of analysis on the results of your topic model

__*Note*__: You can pass the DataFrame column of text reviews to gensim. You do not have to use a generator.

In [0]:
from gensim.models import LdaMulticore
from gensim.corpora import Dictionary

Learn the vocubalary of the yelp data:

In [0]:
id2word = Dictionary(yelp['text_tokens'])

In [0]:
len(id2word.keys())

60596

In [0]:
id2word.filter_extremes(no_below=5, no_above=0.95)

In [0]:
len(id2word.keys())

10598

Create a bag of words representation of the entire corpus

In [0]:
corpus = [id2word.doc2bow(tokens) for tokens in text_tokens]

Your LDA model should be ready for estimation: 

In [0]:
lda = LdaMulticore(corpus=corpus,
                   id2word=id2word,
                   iterations=5,
                   workers=4,
                   num_topics = 3 # You can change this parameter
                  )

In [0]:
lda.print_topics()

[(0,
  '0.009*"place" + 0.009*"food" + 0.009*"like" + 0.007*"great" + 0.006*"good" + 0.005*"time" + 0.005*"it\'s" + 0.005*"service" + 0.004*"don\'t" + 0.004*"i\'m"'),
 (1,
  '0.009*"great" + 0.008*"food" + 0.008*"place" + 0.008*"like" + 0.006*"service" + 0.006*"time" + 0.006*"it\'s" + 0.005*"good" + 0.005*"don\'t" + 0.004*"love"'),
 (2,
  '0.008*"good" + 0.008*"place" + 0.007*"it\'s" + 0.007*"great" + 0.007*"food" + 0.006*"service" + 0.005*"time" + 0.005*"like" + 0.004*"didn\'t" + 0.004*"best"')]

Create 1-2 visualizations of the results

In [0]:
#visualize
import re
words = [re.findall(r'"([^"]*)"',t[1]) for t in lda.print_topics()]


In [0]:
topics = [' '.join(t[0:3]) for t in words]

In [0]:
topics

['place food like', 'great food place', "good place it's"]

In [0]:
import pyLDAvis.gensim

pyLDAvis.enable_notebook()

In [0]:
pyLDAvis.gensim.prepare(lda, corpus, id2word)

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic                                                
1      0.003141  0.003510       1        1  33.416721
2     -0.004998  0.000657       2        1  33.332592
0      0.001857 -0.004167       3        1  33.250687, topic_info=       Term         Freq        Total Category  logprob  loglift
15     like  3237.000000  3237.000000  Default  30.0000  30.0000
174    good  3039.000000  3039.000000  Default  29.0000  29.0000
584     i'm  1524.000000  1524.000000  Default  28.0000  28.0000
201   great  3359.000000  3359.000000  Default  27.0000  27.0000
740    feel   632.000000   632.000000  Default  26.0000  26.0000
..      ...          ...          ...      ...      ...      ...
745    love   425.370209  1550.312134   Topic3  -5.8612  -0.1922
675  didn't   402.886566  1480.700806   Topic3  -5.9155  -0.2005
121  people   358.548279  1161.143799   Topic3  -6.0321  -0.0740
43    staff   353.460571  1232.492798   Topic3  -6.0464  -0.1479
373   order   329.277740  1160.764160   Topic3  -6.1173  -0.1588

[282 rows x 6 columns], token_table=      Topic      Freq       Term
term                            
2125      1  0.414089  "manager"
2125      2  0.276060  "manager"
2125      3  0.276060  "manager"
2414      1  0.210777        'em
2414      2  0.210777        'em
...     ...       ...        ...
769       2  0.403231      worth
769       3  0.300004      worth
949       1  0.247501     you're
949       2  0.322550     you're
949       3  0.429535     you're

[603 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[2, 3, 1])


##                                                         Analysis

     Topic Model, LDA(Latent Dirichlet Allcocation) is  used for uncovering hidden structure, e,g topics of reviews in a collection of texts of the restaurant yelp information. It made the analysis run faster because it reduced the dimensionality of space , it also collected the  documents that best represents the Unsupervised Learning, it gave  the number of clusters of topics, e,g.bgood or bad reviews on a restaurant, the service, and the food.  So by LDA topic modeling, we build clusters of topics.   We can tag the abstract “topics”  that best represents the customers opinions. It got user ratings of each of those subcategories and then train a model specifically to predict food rating for a review. Also by visualizations,  we  really easily can see how individual review contribute the whole review on different parts,such food, place, service.From this analysis, the manager  can  know some useful information what place they do good, what place they need improve such on food, sevice, and so on. It reflected the information to users and the owner. 




## Stretch Goals

Complete one of more of these to push your score towards a three: 
* Incorporate named entity recognition into your analysis
* Compare vectorization methods in the classification section
* Analyze more (or all) of the yelp dataset - this one is v. hard. 
* Use a generator object on the reviews file - this would help you with the analyzing the whole dataset.
* Incorporate any of the other yelp dataset entities in your analysis (business, users, etc.)